const FOOD_DATA = [
  {
    "name":"Burger",
    "brand":"Hawkers",
    "price":2.99,
    "image":"http://www.pngall.com/wp-content/uploads/2016/05/Burger-PNG-Image.png"
  },{
    "name":"Cheese Dip",
    "brand":"Hawkers",
    "price":4.99,
    "image":"https://www.nicepng.com/png/full/336-3368488_cheese-dip-auntie-annes-dips.png"
  },
  {
    "name":"Cola",
    "brand":"Mcdonald",
    "price":1.49,
    "image":"https://cdn-0.imagensemoldes.com.br/wp-content/uploads/2020/05/Pet-2-Litros-Coca-Cola-PNG.png"
  },
  {
    "name":"Fries",
    "brand":"Mcdonald",
    "price":2.99,
    "image":"https://pngimg.com/uploads/fries/fries_PNG75.png"
  },
  {
    "name":"Ice Cream",
    "brand":"Ben & Jerry's",
    "price":9.49,
    "image":"https://i.pinimg.com/564x/ec/5f/ce/ec5fcecd3c6cebd9476bdc003d67de53.jpg"
  },
  {
    "name":"Noodles",
    "brand":"Hawkers",
    "price":4.49,
    "image":"http://www.pngall.com/wp-content/uploads/5/Noodles-PNG-Image.png"
  },
  {
    "name":"Pizza",
    "brand":"Dominos",
    "price":17.99,
    "image":"https://i.pinimg.com/564x/e9/c6/d4/e9c6d42c61aa0b4cd2b771f735e2d5d3.jpg"
  },
  {
    "name":"Sandwich",
    "brand":"Hawkers",
    "price":2.99,
    "image":"http://www.pngreal.com/uploads/1/Grilled-Sandwich-PNG-HD-Quality.png"
  },
  {
    "name":"Wrap",
    "brand":"Subway",
    "price":6.99,
    "image":"http://www.pngmart.com/files/11/Wrap-PNG-Transparent-Image.png"
  }
];

const CATEGORY_DATA = [
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  },
  {
    "icon":"local_pizza"
  }

];
